- .circleci/config.yml
- .github/pull_request_template.md
- .gitignore
- .npmrc
- .nycrc
- .vscode/launch.json
- .vscode/tasks.json
- Dockerfile
- Dockerfile_dev
- README.md
- integration-test.yaml
- package-lock.json
- package.json
- src/common/types.ts
- src/common/utils/logger.ts
- src/job-1/app.ts
- src/job-1/config.js
- src/job-1/daos/job1Dao.ts
- src/job-1/ioc.ts
- src/job-1/job.ts
- src/job-1/knexfile.js
- src/job-1/services/job1Service.ts
- src/job-1/types.ts
- tests/fixtures/job1Fixtures.ts
- tests/integration/job-1/job1Setup.ts
- tests/integration/job-1/job1Tests.ts
- tests/unit/job-1/job1JobTests.ts
- tests/unit/job-1/services/job1ServiceTests.ts
- tsconfig.json
- tslint.json
Worker - https://github.com/departmentfortransport/street-manager-worker/pull/1
Jobs - https://github.com/departmentfortransport/street-manager-jobs/pull/2
Terraform - https://github.com/departmentfortransport/street-manager-terraform/pull/1199
Ops Tools - https://github.com/departmentfortransport/street-manager-ops-tools/pull/174
Ops - https://github.com/departmentfortransport/street-manager-ops/pull/1876
Int - https://github.com/departmentfortransport/street-manager-int/pull/284
**TODO:**
**Structure:**
* Jobs are split by directory i.e. `src/job-1/**`, `src/job-2/**`
* A `src/common` folder is present that will house all common elements i.e. `Logger`
* One Job should never import anything from another Job's sub-folder.
* DB Config is setup per job, because there is no guarantee that …
> feature/SM-5499 - Generic Worker and Jobs Skeleton

- src/job-1/knexfile.js
> fix undefined error

- integration-test.yaml
- src/job-1/daos/job1Dao.ts
> task/Update Postgres Image

- package-lock.json
- package.json
> feature/SM-5547: update data hash

- README.md
> Update README - release process following phase & sprint numbers

- .circleci/config.yml
> SM-6101: Push to preview ECR

- package-lock.json
- package.json
> feature/SM-5619: bump data hash

- tests/integration/generate-sample-inspections/generateSampleInspectionsTests.ts
- tslint.json
> SM-5579: Add linting rules

- package-lock.json
- package.json
- tests/integration/generate-sample-inspections/setup.ts
- tests/integration/helpers/reinstatementHelper.ts
- tests/integration/helpers/workHelper.ts
> SM-5401: Upgrade knex & knex postgis

- package-lock.json
- package.json
> feature/SM-5153: data hash bump

- src/generate-sample-inspections/app.ts
> SM-6322: Add handler to log unhandled promise rejection errors

- src/generate-sample-inspections/app.ts
> SM-6474 - Correctly format unhandled promise rejections

- .circleci/config.yml
> feature/SM-6580-CCI ECR IAM changes

- src/common/services/transactionService.ts
> feature SM-6562-Transaction Service Rejection handler

- integration-test.yaml
> SM-6657 - Update integration test postgres image

- package-lock.json
- package.json
> feature/SM-6774: bump data hash

- package-lock.json
- package.json
> feature/SM-5846-Close a Sample Inspection Target

- integration-test.yaml
> SM-6815 - Bump postgres version for integration tests

- .circleci/config.yml
> correct AWS region env variable

- .npmrc
- package-lock.json
- package.json
> task/SM-7119: fix vulnerabilities

- .npmrc
- package-lock.json
- package.json
swap version of knex postgis to use Street Manager fork
reduce audit level to moderate
> feature/SM-7166: update knex postgis

- .circleci/config.yml
- Dockerfile
- Dockerfile_dev
- integration-test.yaml
- src/generate-sample-inspections/config.js
> SM-7172 - Open source preparation
